name: vertx_dart_sockjs
description: Dart SockJS and Vert.x eventbus JS integration based on SockJS
version: 3.5.0
author: Michel Werren <michel.werren@source-motion.ch>
homepage: https://github.com/wem/vertx-dart-sockjs

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
  js: ^0.6.1
  logging:

dev_dependencies:
  test: ^0.12.20
  quiver: ^0.25.0
  json_object:
