name: vertx_dart_sockjs
description: Dart SockJS and Vert.x eventbus JS integration based on SockJS
version: 0.3.4
author: Michel Werren <michel.werren@source-motion.ch>
homepage: https://github.com/wem/vertx-dart-sockjs

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  js: ^0.6.1
  logging:

dev_dependencies:
  test: ^0.12.20
